# Generated by Django 4.1.7 on 2023-08-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourismapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='destinationdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('descrip', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='product image')),
                ('lo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
