# Generated by Django 4.1.7 on 2023-08-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_customer_payment_tour_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_place', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('joining_place', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('mobile', models.IntegerField(null=True)),
                ('members', models.CharField(max_length=100)),
                ('package', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
