# Generated by Django 4.1.7 on 2023-08-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_bookingdb_delete_booking_delete_customer_delete_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdb',
            name='date',
        ),
    ]
