# Generated by Django 4.1.7 on 2023-08-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_remove_bookingdb_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
