# Generated by Django 4.1.7 on 2023-08-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_feedbackdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdb',
            name='departure_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
